development:
  adapter: postgresql
  encoding: unicode
  database: benja
  pool: 5
  username: benja
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: prueba_1
  pool: 5
  username: benja
  password: 
